//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDictionary.DataLayer.SqlScript {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Domain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Domain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDictionary.DataLayer.SqlScript.Domain", typeof(Domain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DomainId.
        /// </summary>
        internal static string DomainId {
            get {
                return ResourceManager.GetString("DomainId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procGetDomain].
        /// </summary>
        internal static string GetMethod {
            get {
                return ResourceManager.GetString("GetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select [DOMAIN_CATALOG] As[DatabaseName],
        ///	[DOMAIN_SCHEMA] As[SchemaName],
        ///	[DOMAIN_NAME] As[DomainName],
        ///	[DATA_TYPE] As[DataType],
        ///	[DOMAIN_DEFAULT] As[DomainDefault],
        ///	[CHARACTER_MAXIMUM_LENGTH] As[CharacterMaximumLength],
        ///	[CHARACTER_OCTET_LENGTH] As[CharacterOctetLength],
        ///	[NUMERIC_PRECISION] As[NumericPrecision],
        ///	[NUMERIC_PRECISION_RADIX] As[NumericPrecisionRadix],
        ///	[NUMERIC_SCALE] As[NumericScale],
        ///	[DATETIME_PRECISION] As[DateTimePrecision],
        ///	[CHARACTER_SET_CATALOG] As[CharacterSetCatalo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InformationSchema {
            get {
                return ResourceManager.GetString("InformationSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procSetDomain].
        /// </summary>
        internal static string SetMethod {
            get {
                return ResourceManager.GetString("SetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[typeDomain].
        /// </summary>
        internal static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
    }
}
