//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDictionary.Main.Forms.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainAttribute_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainAttribute_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDictionary.Main.Forms.Domain.DomainAttribute.Resource", typeof(DomainAttribute_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Attribute a Composite Type (composed of multiple Simple Types, not Simple).
        /// </summary>
        internal static string IsCompositeType {
            get {
                return ResourceManager.GetString("IsCompositeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Attribute a Derived Value (computed value, not Integral).
        /// </summary>
        internal static string IsDerived {
            get {
                return ResourceManager.GetString("IsDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Attribute an Integral value (distinct or basic value, not Derived).
        /// </summary>
        internal static string IsIntegral {
            get {
                return ResourceManager.GetString("IsIntegral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Attribute is used as a Key (part of a PK, FK, or AK).
        /// </summary>
        internal static string IsKey {
            get {
                return ResourceManager.GetString("IsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Attribute Multi Valued (has multiple values, not single).
        /// </summary>
        internal static string IsMultiValue {
            get {
                return ResourceManager.GetString("IsMultiValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Attribute a Non-Key item (not part of a PK, FK or AK).
        /// </summary>
        internal static string IsNonKey {
            get {
                return ResourceManager.GetString("IsNonKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Attribute a Null-able value (allows Null value).
        /// </summary>
        internal static string IsNullable {
            get {
                return ResourceManager.GetString("IsNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Attribute a Simple Type (cannot be decomposed, not composite).
        /// </summary>
        internal static string IsSimpleType {
            get {
                return ResourceManager.GetString("IsSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Attribute Single Valued (has only one value, not multi-valued).
        /// </summary>
        internal static string IsSingleValue {
            get {
                return ResourceManager.GetString("IsSingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Attribute a valued (not null) attribute..
        /// </summary>
        internal static string IsValued {
            get {
                return ResourceManager.GetString("IsValued", resourceCulture);
            }
        }
    }
}
