using DataDictionary.BusinessLayer.AppCatalog;
using System.ComponentModel;
using System.Data;
using Toolbox.BindingTable;

namespace DataDictionary.Main.Forms.Catalog
{
    partial class DbDomain : ApplicationData
    {

        public override Boolean IsOpenItem(object? item)
        { return bindingDomain.Current is IDomainValue current && ReferenceEquals(current, item); }

        protected DbDomain() : base()
        {
            InitializeComponent();

            SetRowState(bindingDomain, bindingProperties);
            SetIcon(bindingDomain);
            SetTitle(bindingDomain);
        }

        public DbDomain(IDomainValue domainItem) : this()
        {
            DomainIndexName key = new DomainIndexName(domainItem);
            PropertyIndexObject propertyKey = new PropertyIndexObject(key);

            IBindingList data = new BindingView<DomainValue>(BusinessData.CatalogModel.DbDomains, w => key.Equals(w));
            data.ListChanged += ListChanged;

            bindingDomain.DataSource = data;
            bindingDomain.Position = 0;

            if (bindingDomain.Current is IDomainValue current)
            {
                bindingProperties.DataSource = new BindingView<PropertyValue>(BusinessData.CatalogModel.DbProperties, w => propertyKey.Equals(w));
            }

            void ListChanged(Object? sender, ListChangedEventArgs e)
            {
                // This addresses an invalid operation exception fired by CurrencyManager.FindGoodRow on an empty list
                if (e.ListChangedType is ListChangedType.ItemDeleted
                    && sender is IBindingList values
                    && values.Count is 0)
                {
                    bindingDomain.RaiseListChangedEvents = false;
                    bindingProperties.RaiseListChangedEvents = false;

                    // This addresses index out of range exception generated by DataGridView
                    Invoke(() => { extendedPropertiesData.DataSource = null; });
                }
            }
        }

        private void DbDomain_Load(object sender, EventArgs e)
        {
            catalogNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.DatabaseName)));
            schemaNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.SchemaName)));
            domainNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.DomainName)));
            domainDefaultData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.DomainDefault)));

            dataTypeData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.DataType)));
            characterMaximumLengthData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.CharacterMaximumLength)));
            characterOctetLengthData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.CharacterOctetLength)));
            numericPrecisionData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.NumericPrecision)));
            numericPrecisionRadixData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.NumericPrecisionRadix)));
            numericScaleData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.NumericScale)));
            dateTimePrecisionData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.DateTimePrecision)));

            characterSetCatalogData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.CharacterSetCatalog)));
            characterSetSchemaData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.CharacterSetSchema)));
            characterSetNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.CharacterSetName)));

            collationCatalogData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.CollationCatalog)));
            collationSchemaData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.CollationSchema)));
            collationNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingDomain, nameof(IDomainValue.CollationName)));

            extendedPropertiesData.AutoGenerateColumns = false;
            extendedPropertiesData.DataSource = bindingProperties;

            IsLocked(RowState is DataRowState.Detached or DataRowState.Deleted || bindingDomain.Current is not IDomainValue);
        }
    }
}
