using DataDictionary.BusinessLayer.AppCatalog;
using DataDictionary.Main.Enumerations;
using DataDictionary.Resource.Enumerations;
using System.ComponentModel;
using System.Data;
using Toolbox.BindingTable;

namespace DataDictionary.Main.Forms.Catalog
{
    partial class DbRoutineParameter : ApplicationData
    {

        public Boolean IsOpenItem(object? item)
        { return bindingParameter.Current is IRoutineParameterValue current && ReferenceEquals(current, item); }

        protected DbRoutineParameter() : base()
        {
            InitializeComponent();

            SetRowState(bindingParameter, bindingProperties);
            SetTitle(bindingParameter);
        }

        public DbRoutineParameter(IRoutineParameterValue parameterItem) : this()
        {
            RoutineParameterIndexName key = new RoutineParameterIndexName(parameterItem);
            PropertyIndexObject propertyKey = new PropertyIndexObject(key);
            
            IBindingList data = new BindingView<RoutineParameterValue>(BusinessData.CatalogModel.DbRoutineParameters, w => key.Equals(w));
            data.ListChanged += ListChanged;

            bindingParameter.DataSource = data;
            bindingParameter.Position = 0;

            if (bindingParameter.Current is IRoutineParameterValue current)
            {
                bindingProperties.DataSource = new BindingView<PropertyValue>(BusinessData.CatalogModel.DbProperties, w => propertyKey.Equals(w));
            }

            void ListChanged(Object? sender, ListChangedEventArgs e)
            {
                // This addresses an invalid operation exception fired by CurrencyManager.FindGoodRow on an empty list
                if (e.ListChangedType is ListChangedType.ItemDeleted
                    && sender is IBindingList values
                    && values.Count is 0)
                {
                    bindingParameter.RaiseListChangedEvents = false;
                    bindingProperties.RaiseListChangedEvents = false;

                    // This addresses index out of range exception generated by DataGridView
                    Invoke(() => { extendedPropertiesData.DataSource = null; });
                }
            }
        }

        private void DbRoutineParameter_Load(object sender, EventArgs e)
        {
            catalogNameData.DataBindings.Add(new Binding(nameof(catalogNameData.Text), bindingParameter, nameof(IRoutineParameterValue.DatabaseName)));
            schemaNameData.DataBindings.Add(new Binding(nameof(schemaNameData.Text), bindingParameter, nameof(IRoutineParameterValue.SchemaName)));
            routineNameData.DataBindings.Add(new Binding(nameof(routineNameData.Text), bindingParameter, nameof(IRoutineParameterValue.RoutineName)));
            parameterNameData.DataBindings.Add(new Binding(nameof(parameterNameData.Text), bindingParameter, nameof(IRoutineParameterValue.ParameterName)));
            ordinalPositionData.DataBindings.Add(new Binding(nameof(ordinalPositionData.Text), bindingParameter, nameof(IRoutineParameterValue.OrdinalPosition)));

            dataTypeData.DataBindings.Add(new Binding(nameof(parameterNameData.Text), bindingParameter, nameof(IRoutineParameterValue.DataType)));
            characterMaximumLengthData.DataBindings.Add(new Binding(nameof(characterMaximumLengthData.Text), bindingParameter, nameof(IRoutineParameterValue.CharacterMaximumLength)));
            characterOctetLengthData.DataBindings.Add(new Binding(nameof(characterOctetLengthData.Text), bindingParameter, nameof(IRoutineParameterValue.CharacterOctetLength)));
            numericPrecisionData.DataBindings.Add(new Binding(nameof(numericPrecisionData.Text), bindingParameter, nameof(IRoutineParameterValue.NumericPrecision)));
            numericPrecisionRadixData.DataBindings.Add(new Binding(nameof(numericPrecisionRadixData.Text), bindingParameter, nameof(IRoutineParameterValue.NumericPrecisionRadix)));
            numericScaleData.DataBindings.Add(new Binding(nameof(numericScaleData.Text), bindingParameter, nameof(IRoutineParameterValue.NumericScale)));
            dateTimePrecisionData.DataBindings.Add(new Binding(nameof(dateTimePrecisionData.Text), bindingParameter, nameof(IRoutineParameterValue.DateTimePrecision)));

            characterSetCatalogData.DataBindings.Add(new Binding(nameof(characterSetCatalogData.Text), bindingParameter, nameof(IRoutineParameterValue.CharacterSetCatalog)));
            characterSetSchemaData.DataBindings.Add(new Binding(nameof(characterSetSchemaData.Text), bindingParameter, nameof(IRoutineParameterValue.CharacterSetSchema)));
            characterSetNameData.DataBindings.Add(new Binding(nameof(characterSetNameData.Text), bindingParameter, nameof(IRoutineParameterValue.CharacterSetName)));

            collationCatalogData.DataBindings.Add(new Binding(nameof(collationCatalogData.Text), bindingParameter, nameof(IRoutineParameterValue.CollationCatalog)));
            collationSchemaData.DataBindings.Add(new Binding(nameof(collationSchemaData.Text), bindingParameter, nameof(IRoutineParameterValue.CollationSchema)));
            collationNameData.DataBindings.Add(new Binding(nameof(collationNameData.Text), bindingParameter, nameof(IRoutineParameterValue.CollationName)));

            domainCatalogData.DataBindings.Add(new Binding(nameof(domainCatalogData.Text), bindingParameter, nameof(IRoutineParameterValue.CollationCatalog)));
            domainSchemaData.DataBindings.Add(new Binding(nameof(domainSchemaData.Text), bindingParameter, nameof(IRoutineParameterValue.DomainSchema)));
            domainNameData.DataBindings.Add(new Binding(nameof(domainNameData.Text), bindingParameter, nameof(IRoutineParameterValue.DomainName)));

            extendedPropertiesData.AutoGenerateColumns = false;
            extendedPropertiesData.DataSource = bindingProperties;

            IsLocked(RowState is DataRowState.Detached or DataRowState.Deleted || bindingParameter.Current is not IRoutineParameterValue);
        }
    }
}
