using DataDictionary.BusinessLayer.AppCatalog;
using DataDictionary.Main.Enumerations;
using DataDictionary.Resource.Enumerations;
using System.ComponentModel;
using System.Data;
using Toolbox.BindingTable;

namespace DataDictionary.Main.Forms.Catalog
{
    partial class DbRoutine : ApplicationData
    {
        public override Boolean IsOpenItem(object? item)
        { return bindingRoutine.Current is IRoutineValue current && ReferenceEquals(current, item); }

        protected DbRoutine() : base()
        {
            InitializeComponent();

            SetRowState(
                bindingRoutine,
                bindingParameters,
                bindingProperties,
                bindingDependencies);
            SetTitle(bindingRoutine);
        }

        public DbRoutine(IRoutineValue routineItem) : this()
        {
            RoutineIndexName key = new RoutineIndexName(routineItem);
            PropertyIndexObject propertyKey = new PropertyIndexObject(key);

            IBindingList data = new BindingView<RoutineValue>(BusinessData.CatalogModel.DbRoutines, w => key.Equals(w));
            data.ListChanged += ListChanged;

            bindingRoutine.DataSource = data;
            bindingRoutine.Position = 0;

            if (bindingRoutine.Current is IRoutineValue current)
            {
                ReferenceIndexName referenceName = new ReferenceIndexName(current);
                bindingParameters.DataSource = new BindingView<RoutineParameterValue>(BusinessData.CatalogModel.DbRoutineParameters, w => key.Equals(w), o => o.OrdinalPosition ?? 0);
                bindingProperties.DataSource = new BindingView<PropertyValue>(BusinessData.CatalogModel.DbProperties, w => propertyKey.Equals(w));
                bindingDependencies.DataSource = new BindingView<ReferenceValue>(BusinessData.CatalogModel.DbReferences, w => referenceName.Equals(w));
            }

            void ListChanged(Object? sender, ListChangedEventArgs e)
            {
                // This addresses an invalid operation exception fired by CurrencyManager.FindGoodRow on an empty list
                if (e.ListChangedType is ListChangedType.ItemDeleted
                    && sender is IBindingList values
                    && values.Count is 0)
                {
                    bindingRoutine.RaiseListChangedEvents = false;
                    bindingProperties.RaiseListChangedEvents = false;
                    bindingParameters.RaiseListChangedEvents = false;
                    bindingDependencies.RaiseListChangedEvents = false;

                    // This addresses index out of range exception generated by DataGridView
                    Invoke(() => { extendedPropertiesData.DataSource = null; });
                    Invoke(() => { parametersData.DataSource = null; });
                    Invoke(() => { dependenciesData.DataSource = null; });
                }
            }
        }

        private void DbRoutine_Load(object sender, EventArgs e)
        {
            catalogNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingRoutine, nameof(IRoutineValue.DatabaseName)));
            schemaNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingRoutine, nameof(IRoutineValue.SchemaName)));
            routineNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingRoutine, nameof(IRoutineValue.RoutineName)));
            routineTypeData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingRoutine, nameof(IRoutineValue.RoutineType)));
            isSystemData.DataBindings.Add(new Binding(nameof(CheckBox.Checked), bindingRoutine, nameof(IRoutineValue.IsSystem)));

            extendedPropertiesData.AutoGenerateColumns = false;
            extendedPropertiesData.DataSource = bindingProperties;

            parametersData.AutoGenerateColumns = false;
            parametersData.DataSource = bindingParameters;

            dependenciesData.AutoGenerateColumns = false;
            dependenciesData.DataSource = bindingDependencies;

            IsLocked(RowState is DataRowState.Detached or DataRowState.Deleted || bindingRoutine.Current is not IRoutineValue);
        }
    }
}
