using DataDictionary.BusinessLayer.AppCatalog;
using DataDictionary.Main.Enumerations;
using DataDictionary.Resource.Enumerations;
using System.ComponentModel;
using System.Data;
using Toolbox.BindingTable;

namespace DataDictionary.Main.Forms.Catalog
{
    partial class DbSchema : ApplicationData, IApplicationDataForm
    {
        public Boolean IsOpenItem(object? item)
        { return bindingSchema.Current is ISchemaValue current && ReferenceEquals(current, item); }

        protected DbSchema() : base()
        {
            InitializeComponent();

            SetRowState(bindingSchema, bindingProperties);
            SetTitle(bindingSchema);
        }

        public DbSchema(ISchemaValue schemaItem) : this()
        {
            SchemaIndexName key = new SchemaIndexName(schemaItem);
            PropertyIndexObject propertyKey = new PropertyIndexObject(key);

            IBindingList data = new BindingView<SchemaValue>(BusinessData.CatalogModel.DbSchemta, w => key.Equals(w));
            data.ListChanged += ListChanged;

            bindingSchema.DataSource = data;
            bindingSchema.Position = 0;

            if (bindingSchema.Current is ISchemaValue current)
            {
                bindingProperties.DataSource = new BindingView<PropertyValue>(BusinessData.CatalogModel.DbProperties, w => propertyKey.Equals(w));
            }

            void ListChanged(Object? sender, ListChangedEventArgs e)
            {
                // This addresses an invalid operation exception fired by CurrencyManager.FindGoodRow on an empty list
                if (e.ListChangedType is ListChangedType.ItemDeleted
                    && sender is IBindingList values
                    && values.Count is 0)
                {
                    bindingSchema.RaiseListChangedEvents = false;
                    bindingProperties.RaiseListChangedEvents = false;

                    // This addresses index out of range exception generated by DataGridView
                    Invoke(() => { extendedPropertiesData.DataSource = null; });
                }
            }
        }

        private void DbSchema_Load(object sender, EventArgs e)
        {
            ISchemaValue bindingNames;
            catalogNameData.DataBindings.Add(new Binding(nameof(catalogNameData.Text), bindingSchema, nameof(bindingNames.DatabaseName)));
            schemaNameData.DataBindings.Add(new Binding(nameof(schemaNameData.Text), bindingSchema, nameof(bindingNames.SchemaName)));
            isSystemData.DataBindings.Add(new Binding(nameof(isSystemData.Checked), bindingSchema, nameof(bindingNames.IsSystem)));
            errorProvider.SetError(schemaNameData.ErrorControl, String.Empty);

            extendedPropertiesData.AutoGenerateColumns = false;
            extendedPropertiesData.DataSource = bindingProperties;

            IsLocked(RowState is DataRowState.Detached or DataRowState.Deleted || bindingSchema.Current is not ISchemaValue);
        }

    }
}
