using DataDictionary.BusinessLayer.AppCatalog;
using DataDictionary.BusinessLayer.AppModel;
using DataDictionary.BusinessLayer.ToolSet;
using DataDictionary.Main.Controls;
using DataDictionary.Main.Enumerations;
using DataDictionary.Main.Messages;
using DataDictionary.Resource.Enumerations;
using System.ComponentModel;
using System.Data;
using Toolbox.BindingTable;

namespace DataDictionary.Main.Forms.Catalog
{
    partial class DbTableColumn : ApplicationData, IApplicationDataForm
    {
        public Boolean IsOpenItem(object? item)
        { return bindingColumn.Current is ITableColumnValue current && ReferenceEquals(current, item); }

        public DbTableColumn() : base()
        {
            InitializeComponent();

            SetRowState(bindingColumn, bindingProperties);
            SetTitle(bindingColumn);
            SetCommand(ScopeType.DatabaseTableColumn, Enumerations.CommandType.Export);

            CommandButtons[Enumerations.CommandType.Export].Text = "to Model";
            CommandButtons[Enumerations.CommandType.Export].DropDown = exportOptions;
            exportAttributes.Image = ScopeType.ModelAttribute.GetImage(Enumerations.CommandType.Add);
        }

        public DbTableColumn(ITableColumnValue columnItem) : this()
        {
            TableColumnIndexName key = new TableColumnIndexName(columnItem);
            PropertyIndexObject propertyKey = new PropertyIndexObject(key);

            IBindingList data = new BindingView<TableColumnValue>(BusinessData.CatalogModel.DbTableColumns, w => key.Equals(w));
            data.ListChanged += ListChanged;

            bindingColumn.DataSource = data;
            bindingColumn.Position = 0;

            if (bindingColumn.Current is ITableColumnValue current)
            { bindingProperties.DataSource = new BindingView<BusinessLayer.AppCatalog.PropertyValue>(BusinessData.CatalogModel.DbProperties, w => propertyKey.Equals(w)); }

            void ListChanged(Object? sender, ListChangedEventArgs e)
            {
                // This addresses an invalid operation exception fired by CurrencyManager.FindGoodRow on an empty list
                if (e.ListChangedType is ListChangedType.ItemDeleted
                    && sender is IBindingList values
                    && values.Count is 0)
                {
                    bindingColumn.RaiseListChangedEvents = false;
                    bindingProperties.RaiseListChangedEvents = false;

                    // This addresses index out of range exception generated by DataGridView
                    Invoke(() => { extendedPropertiesData.DataSource = null; });
                }
            }
        }

        private void DbColumn_Load(object sender, EventArgs e)
        {
            catalogNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.DatabaseName)));
            schemaNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.SchemaName)));
            tableNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.TableName)));
            columnNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.ColumnName)));
            ordinalPositionData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.OrdinalPosition)));
            columnDefaultData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.ColumnDefault)));
            columnComputedData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.ComputedDefinition)));
            isNullableData.DataBindings.Add(new Binding(nameof(CheckBox.Checked), bindingColumn, nameof(ITableColumnValue.IsNullable), true, DataSourceUpdateMode.OnValidation, false));
            isComputedData.DataBindings.Add(new Binding(nameof(CheckBox.Checked), bindingColumn, nameof(ITableColumnValue.IsComputed), true, DataSourceUpdateMode.OnValidation, false));

            dataTypeData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.DataType)));
            characterMaximumLengthData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CharacterMaximumLength)));
            characterOctetLengthData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CharacterOctetLength)));
            numericPrecisionData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.NumericPrecision)));
            numericPrecisionRadixData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.NumericPrecisionRadix)));
            numericScaleData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.NumericScale)));
            dateTimePrecisionData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.DateTimePrecision)));

            characterSetCatalogData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CharacterSetCatalog)));
            characterSetSchemaData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CharacterSetSchema)));
            characterSetNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CharacterSetName)));

            collationCatalogData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CollationCatalog)));
            collationSchemaData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CollationSchema)));
            collationNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CollationName)));

            domainCatalogData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.CollationCatalog)));
            domainSchemaData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.DomainSchema)));
            domainNameData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.DomainName)));

            generatedAlwayTypeData.DataBindings.Add(new Binding(nameof(TextBox.Text), bindingColumn, nameof(ITableColumnValue.GeneratedAlwayType)));
            isIdentityData.DataBindings.Add(new Binding(nameof(CheckBox.Checked), bindingColumn, nameof(ITableColumnValue.IsIdentity), true, DataSourceUpdateMode.OnValidation, false));
            isHiddenData.DataBindings.Add(new Binding(nameof(CheckBox.Checked), bindingColumn, nameof(ITableColumnValue.IsHidden), true, DataSourceUpdateMode.OnValidation, false));

            extendedPropertiesData.AutoGenerateColumns = false;
            extendedPropertiesData.DataSource = bindingProperties;

            IsLocked(RowState is DataRowState.Detached or DataRowState.Deleted || bindingColumn.Current is not ITableColumnValue);
        }

        private void ExportAttributes_Click(object sender, EventArgs e)
        {
            if (bindingColumn.Current is TableColumnValue current)
            {
                TableColumnAttribute columnAttribute = new TableColumnAttribute(current)
                {
                    GetAlias = BusinessData.CatalogModel.DbTableColumns.GetAlias,
                    GetCatalogProperty = BusinessData.CatalogModel.DbProperties.GetProperty,
                    GetModelProperty = BusinessData.Model.Properties.TryGetValue
                };

                IAttributeValue attribute = BusinessData.Model.Attribute.Import(columnAttribute);

                Activate(() => new Forms.Model.Attribute(attribute));
                SendMessage(new RefreshNavigation());
            }
        }
    }
}
