//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDictionary.DataLayer.AppCatalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Routine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Routine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDictionary.DataLayer.AppCatalog.Routine", typeof(Routine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procGetRoutine].
        /// </summary>
        internal static string GetProcedure {
            get {
                return ResourceManager.GetString("GetProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.sp_creatediagram, dbo.sp_renamediagram, dbo.sp_alterdiagram, dbo.sp_dropdiagram, dbo.fn_diagramobjects, dbo.sp_helpdiagrams, dbo.sp_helpdiagramdefinition, dbo.sp_upgraddiagrams.
        /// </summary>
        internal static string IsSystem {
            get {
                return ResourceManager.GetString("IsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RoutineId.
        /// </summary>
        internal static string RoutineId {
            get {
                return ResourceManager.GetString("RoutineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procSetRoutine].
        /// </summary>
        internal static string SetProcedure {
            get {
                return ResourceManager.GetString("SetProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[typeRoutine].
        /// </summary>
        internal static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select	[ROUTINE_CATALOG] As [DatabaseName],
        ///		[ROUTINE_SCHEMA] As [SchemaName],
        ///		[ROUTINE_NAME] As [RoutineName],
        ///		Case
        ///			When [ROUTINE_TYPE] In (&apos;PROCEDURE&apos;) Then &apos;Procedure&apos;
        ///			When [ROUTINE_TYPE] In (&apos;FUNCTION&apos;) Then &apos;Function&apos;
        ///			Else [ROUTINE_TYPE] 
        ///			End As [RoutineType]
        ///From	[INFORMATION_SCHEMA].[ROUTINES]
        ///.
        /// </summary>
        internal static string TSql_InformationSchema {
            get {
                return ResourceManager.GetString("TSql_InformationSchema", resourceCulture);
            }
        }
    }
}
