//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDictionary.DataLayer.AppCatalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Schema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Schema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDictionary.DataLayer.AppCatalog.Schema", typeof(Schema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procGetSchema].
        /// </summary>
        internal static string GetProcedure {
            get {
                return ResourceManager.GetString("GetProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo, sys, db_owner, db_accessadmin, db_securityadmin, db_ddladmin, db_backupoperator, db_datareader, db_datawriter, db_denydatareader, db_denydatawriter, INFORMATION_SCHEMA, guest.
        /// </summary>
        internal static string IsSystem {
            get {
                return ResourceManager.GetString("IsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SchemaId.
        /// </summary>
        internal static string SchemaId {
            get {
                return ResourceManager.GetString("SchemaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procSetSchema].
        /// </summary>
        internal static string SetProcedure {
            get {
                return ResourceManager.GetString("SetProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[typeSchema].
        /// </summary>
        internal static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Remember: Resource files do not update until they are saved directly.
        ///Select	[CATALOG_NAME] As [DatabaseName],
        ///		[SCHEMA_NAME] As [SchemaName]
        ///From	[INFORMATION_SCHEMA].[SCHEMATA].
        /// </summary>
        internal static string TSql_InformationSchema {
            get {
                return ResourceManager.GetString("TSql_InformationSchema", resourceCulture);
            }
        }
    }
}
