//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDictionary.DataLayer.AppCatalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TableColumn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TableColumn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDictionary.DataLayer.AppCatalog.TableColumn", typeof(TableColumn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procGetTableColumn].
        /// </summary>
        internal static string GetProcedure {
            get {
                return ResourceManager.GetString("GetProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procSetTableColumn].
        /// </summary>
        internal static string SetProcedure {
            get {
                return ResourceManager.GetString("SetProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[typeTableColumn].
        /// </summary>
        internal static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Remember: Resource files do not update until they are saved directly.
        ///Select	I.[TABLE_CATALOG] As [DatabaseName],
        ///		I.[TABLE_SCHEMA] As [SchemaName],
        ///		I.[TABLE_NAME] As [TableName],
        ///		Case
        ///		When Exists(Select [history_table_id] From [Sys].[tables] Where [object_id] = C.[object_id] And [history_table_id] is Not Null) Then &apos;Temporal Table&apos;
        ///		When Exists(Select [object_id] From [Sys].[tables] Where [history_table_id] = C.[object_id] And [object_id] is Not Null) Then &apos;History Table&apos;
        ///		When T.[TABLE_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSql_InformationSchema {
            get {
                return ResourceManager.GetString("TSql_InformationSchema", resourceCulture);
            }
        }
    }
}
