//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDictionary.DataLayer.AppCatalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Table {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Table() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDictionary.DataLayer.AppCatalog.Table", typeof(Table).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procGetTable].
        /// </summary>
        internal static string GetProcedure {
            get {
                return ResourceManager.GetString("GetProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[procSetTable].
        /// </summary>
        internal static string SetProcedure {
            get {
                return ResourceManager.GetString("SetProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @TableId.
        /// </summary>
        internal static string TableId {
            get {
                return ResourceManager.GetString("TableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppCatalog].[typeTable].
        /// </summary>
        internal static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select	I.[TABLE_CATALOG] As [DatabaseName],
        ///		I.[TABLE_SCHEMA] As [SchemaName],
        ///		I.[TABLE_NAME] As [TableName],
        ///		Case
        ///			When H.[object_id] is Not Null Then &apos;History Table&apos;
        ///			When T.[history_table_id] is Not Null Then &apos;Temporal Table&apos;
        ///			When I.[TABLE_TYPE] in (&apos;BASE TABLE&apos;) Then &apos;Table&apos;
        ///			When I.[TABLE_TYPE] in (&apos;VIEW&apos;) Then &apos;View&apos;
        ///			Else I.[TABLE_TYPE]
        ///			End As [TableType]
        ///From	[INFORMATION_SCHEMA].[TABLES] I
        ///	Left Join [sys].[Tables] T
        ///	On	I.[TABLE_SCHEMA] = Object_Schema_Name(T.[object [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSql_InformationSchema {
            get {
                return ResourceManager.GetString("TSql_InformationSchema", resourceCulture);
            }
        }
    }
}
