<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Copyright>© 2023 William Howard, All Rights Reserved</Copyright>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Authors>William Howard</Authors>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <None Include="VersionNumber.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VersionNumber.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataDictionary.Resource\DataDictionary.Resource.csproj" />
    <ProjectReference Include="..\Toolbox.BindingTable\Toolbox.BindingTable.csproj" />
    <ProjectReference Include="..\Toolbox.DbContext\Toolbox.DbContext.csproj" />
    <ProjectReference Include="..\Toolbox.Threading\Toolbox.Threading.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SqlScript\Catalog.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Catalog.resx</DependentUpon>
    </Compile>
    <Compile Update="DatabaseData\DbScript.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DbScript.resx</DependentUpon>
    </Compile>
    <Compile Update="SqlScript\Parameter.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Parameter.resx</DependentUpon>
    </Compile>
    <Compile Update="VersionNumber.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VersionNumber.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="SqlScript\Catalog.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Catalog.Designer.cs</LastGenOutput>
      <CustomToolNamespace></CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="DatabaseData\DbScript.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>DbScript.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="SqlScript\Parameter.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Parameter.Designer.cs</LastGenOutput>
      <CustomToolNamespace></CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="VersionNumber.tt">
      <LastGenOutput>VersionNumber.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AppLibrary\" />
    <Folder Include="AppModel\" />
    <Folder Include="AppScript\" />
  </ItemGroup>

</Project>
