<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Copyright>© 2025 William Howard, All Rights Reserved</Copyright>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Authors>William Howard</Authors>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AppCatalog\Catalog.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Constraint.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Domain.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Property.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Reference.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Routine.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\RoutineColumn.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\RoutineParameter.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Schema.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Table.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\TableColumn.TSql.InformationSchema.sql" />
  </ItemGroup>

  <ItemGroup>
    <None Include="VersionNumber.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VersionNumber.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataDictionary.Resource\DataDictionary.Resource.csproj" />
    <ProjectReference Include="..\Toolbox.BindingTable\Toolbox.BindingTable.csproj" />
    <ProjectReference Include="..\Toolbox.DbContext\Toolbox.DbContext.csproj" />
    <ProjectReference Include="..\Toolbox.Threading\Toolbox.Threading.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Temporal.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Temporal.resx</DependentUpon>
    </Compile>
    <Compile Update="VersionNumber.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VersionNumber.tt</DependentUpon>
    </Compile>
    <Compile Update="WriteData.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WriteData.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Temporal.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Temporal.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="WriteData.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WriteData.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="VersionNumber.tt">
      <LastGenOutput>VersionNumber.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AppCatalog\Catalog.TSql.InformationSchema.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="AppCatalog\Constraint.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\ConstraintColumn.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Domain.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Property.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Reference.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Routine.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\RoutineColumn.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\RoutineParameter.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Schema.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Table.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\TableColumn.TSql.InformationSchema.sql" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ProofOfConcept\" />
  </ItemGroup>

</Project>
