<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Copyright>© 2025 William Howard, All Rights Reserved</Copyright>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Authors>William Howard</Authors>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AppCatalog\Catalog.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Constraint.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Domain.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Property.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Reference.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Routine.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\RoutineColumn.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\RoutineParameter.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Schema.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\Table.TSql.InformationSchema.sql" />
    <None Remove="AppCatalog\TableColumn.TSql.InformationSchema.sql" />
  </ItemGroup>

  <ItemGroup>
    <None Include="VersionNumber.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VersionNumber.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataDictionary.Resource\DataDictionary.Resource.csproj" />
    <ProjectReference Include="..\Toolbox.BindingTable\Toolbox.BindingTable.csproj" />
    <ProjectReference Include="..\Toolbox.DbContext\Toolbox.DbContext.csproj" />
    <ProjectReference Include="..\Toolbox.Threading\Toolbox.Threading.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AppSecurity\Authorization.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Authorization.resx</DependentUpon>
    </Compile>
    <Compile Update="AppSecurity\AuthorizationSecurable.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AuthorizationSecurable.resx</DependentUpon>
    </Compile>
    <Compile Update="AppSecurity\Principal.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Principal.resx</DependentUpon>
    </Compile>
    <Compile Update="AppSecurity\Role.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Role.resx</DependentUpon>
    </Compile>
    <Compile Update="AppSecurity\RoleMembership.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RoleMembership.resx</DependentUpon>
    </Compile>
    <Compile Update="AppSecurity\Securable.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Securable.resx</DependentUpon>
    </Compile>
    <Compile Update="AppSecurity\SecurableOwner.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SecurableOwner.resx</DependentUpon>
    </Compile>
    <Compile Update="AppSecurity\SecurablePermission.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SecurablePermission.resx</DependentUpon>
    </Compile>
    <Compile Update="LibraryData\LibraryMember.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LibraryMember.resx</DependentUpon>
    </Compile>
    <Compile Update="LibraryData\LibrarySource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LibrarySource.resx</DependentUpon>
    </Compile>
    <Compile Update="ScriptingData\ScriptingAttribute.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ScriptingAttribute.resx</DependentUpon>
    </Compile>
    <Compile Update="ScriptingData\ScriptingNode.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ScriptingNode.resx</DependentUpon>
    </Compile>
    <Compile Update="ScriptingData\ScriptingPath.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ScriptingPath.resx</DependentUpon>
    </Compile>
    <Compile Update="ScriptingData\ScriptingTemplate.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ScriptingTemplate.resx</DependentUpon>
    </Compile>
    <Compile Update="Temporal.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Temporal.resx</DependentUpon>
    </Compile>
    <Compile Update="VersionNumber.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VersionNumber.tt</DependentUpon>
    </Compile>
    <Compile Update="WriteData.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WriteData.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="AppSecurity\Authorization.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Authorization.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AppSecurity\AuthorizationSecurable.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AuthorizationSecurable.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AppSecurity\Principal.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Principal.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AppSecurity\Role.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Role.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AppSecurity\RoleMembership.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>RoleMembership.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AppSecurity\Securable.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Securable.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AppSecurity\SecurableOwner.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SecurableOwner.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="AppSecurity\SecurablePermission.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SecurablePermission.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="LibraryData\LibraryMember.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>LibraryMember.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="LibraryData\LibrarySource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>LibrarySource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ScriptingData\ScriptingAttribute.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ScriptingAttribute.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ScriptingData\ScriptingNode.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ScriptingNode.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ScriptingData\ScriptingPath.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ScriptingPath.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ScriptingData\ScriptingTemplate.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ScriptingTemplate.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Temporal.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Temporal.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="WriteData.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WriteData.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="VersionNumber.tt">
      <LastGenOutput>VersionNumber.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AppLibrary\" />
    <Folder Include="AppScript\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AppCatalog\Catalog.TSql.InformationSchema.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="AppCatalog\Constraint.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\ConstraintColumn.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Domain.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Property.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Reference.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Routine.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\RoutineColumn.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\RoutineParameter.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Schema.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\Table.TSql.InformationSchema.sql" />
    <EmbeddedResource Include="AppCatalog\TableColumn.TSql.InformationSchema.sql" />
  </ItemGroup>

</Project>
