using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataDictionary.BusinessLayer
{
    partial class BusinessLayerData
    {
        /// <summary>
        /// Holds a Message generated by the Database.
        /// </summary>
        public class MessageItem
        {
            SqlError message;

            /// <inheritdoc cref="SqlError.State"/>
            public Byte State { get { return message.State; } }

            /// <inheritdoc cref="SqlError.Number"/>
            public Int32 Number { get { return message.Number; } }

            /// <inheritdoc cref="SqlError.Procedure"/>
            public String Procedure { get { return message.Procedure; } }

            /// <inheritdoc cref="SqlError.Message"/>
            public String Message { get { return message.Message; } }

            internal MessageItem(SqlError error)
            { message = error; }
        }
    }
}
