using Microsoft.Data.SqlClient;
using System.ComponentModel;

namespace DataDictionary.BusinessLayer
{
    partial class BusinessLayerData
    {
        /// <summary>
        /// Holds a Message generated by the Database.
        /// </summary>
        public class MessageItem : IDataErrorInfo
        {
            SqlError message;

            /// <inheritdoc cref="SqlError.State"/>
            public Byte State { get { return message.State; } }

            /// <inheritdoc cref="SqlError.Number"/>
            public Int32 Number { get { return message.Number; } }

            /// <inheritdoc cref="SqlError.Procedure"/>
            public String Procedure { get { return message.Procedure; } }

            /// <inheritdoc cref="SqlError.Message"/>
            public String Message { get { return message.Message; } }

            /// <inheritdoc cref="IDataErrorInfo.Error"/>
            public String Error
            {
                get
                {
                    if (State > 10)
                    { return message.Message; }
                    else { return String.Empty; }
                }
            }

            /// <summary>
            /// Not Supported. Only Row Level errors are returned.
            /// </summary>
            /// <param name="columnName"></param>
            /// <returns></returns>
            public String this[String columnName] { get { return String.Empty; } }

            internal MessageItem(SqlError error)
            { message = error; }
        }
    }
}
