// Ignore Spelling: Utc

using DataDictionary.BusinessLayer.DbWorkItem;
using DataDictionary.BusinessLayer.ToolSet;
using Toolbox.BindingTable;
using Toolbox.Threading;

namespace DataDictionary.BusinessLayer.AppModel
{
    /// <summary>
    /// Interface representing Model Attribute data
    /// </summary>
    public interface IAttribute :
        ILoadData<IAttributeIndex>, ISaveData<IAttributeIndex>,
        ILoadData<IModelIndex>, ISaveData<IModelIndex>,
        IBindListChanged,
        IGetTemporal<IModelIndex>, IGetTemporal<IAttributeIndex>
    {
        /// <summary>
        /// List of Attributes within the Model.
        /// </summary>
        IAttributeData Values { get; }

        /// <summary>
        /// List of Aliases for the Attributes within the Model.
        /// </summary>
        IAttributeAliasData Aliases { get; }

        /// <summary>
        /// List of Properties for the Attributes within the Model.
        /// </summary>
        IAttributePropertyData Properties { get; }

        /// <summary>
        /// List of Definitions for the Attributes within the Model.
        /// </summary>
        IAttributeDefinitionData Definitions { get; }

        /// <summary>
        /// List of Subject Areas for the Attributes within the Model.
        /// </summary>
        IAttributeSubjectAreaData SubjectArea { get; }

        /// <summary>
        /// Finds the Attributes that match the Alias Index.
        /// </summary>
        /// <param name="aliasIndex"></param>
        /// <returns></returns>
        IEnumerable<IAttributeValue> FindAttribute(IAliasIndexName aliasIndex);

        /// <summary>
        /// Imports a TableColumnAttribute into the list of Attributes
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        /// <remarks>
        /// If the Attribute generated by TableColumnAttribute already exist by Alias,
        /// the source is copied into the existing Attribute where values don't already exist.
        /// Otherwise the TableColumnAttribute is transformed into a Model Attribute.
        /// Both cases return the Attribute that was added or updated.
        /// </remarks>
        IAttributeValue Import(AppCatalog.TableColumnAttribute source);

        /// <summary>
        /// Returns an empty IAttribute.
        /// </summary>
        /// <returns></returns>
        public static IAttribute Create()
        { return new Attribute(); }
    }

    class Attribute : IAttribute, IDataTableFile
    {
        /// <inheritdoc/>
        public IAttributeData Values { get { return attributeValues; } }
        private readonly AttributeData attributeValues;

        /// <inheritdoc/>
        public IAttributeAliasData Aliases { get { return aliasValues; } }
        private readonly AttributeAliasData aliasValues;

        /// <inheritdoc/>
        public IAttributePropertyData Properties { get { return propertyValues; } }
        private readonly AttributePropertyData propertyValues;

        /// <inheritdoc/>
        public IAttributeDefinitionData Definitions { get { return definitionValues; } }
        private readonly AttributeDefinitionData definitionValues;

        /// <inheritdoc/>
        public IAttributeSubjectAreaData SubjectArea { get { return subjectAreaValues; } }
        private readonly AttributeSubjectAreaData subjectAreaValues;

        /// <inheritdoc/>
        public Boolean RaiseListChangedEvents
        {
            get
            {
                return attributeValues.RaiseListChangedEvents
                    && aliasValues.RaiseListChangedEvents
                    && propertyValues.RaiseListChangedEvents
                    && definitionValues.RaiseListChangedEvents
                    && subjectAreaValues.RaiseListChangedEvents;
            }
            set
            {
                attributeValues.RaiseListChangedEvents = value;
                aliasValues.RaiseListChangedEvents = value;
                propertyValues.RaiseListChangedEvents = value;
                definitionValues.RaiseListChangedEvents = value;
                subjectAreaValues.RaiseListChangedEvents = value;
            }
        }

        public Attribute() : base()
        {
            attributeValues = new AttributeData();
            aliasValues = new AttributeAliasData();
            propertyValues = new AttributePropertyData();
            definitionValues = new AttributeDefinitionData();
            subjectAreaValues = new AttributeSubjectAreaData();
        }

        #region ILoadData, ISaveData
        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Load(IDatabaseWork factory, IModelIndex dataKey)
        {
            List<WorkItem> work = new List<WorkItem>();
            work.AddRange(Delete(dataKey));
            work.AddRange(attributeValues.Load(factory, dataKey));
            work.AddRange(aliasValues.Load(factory, dataKey));
            work.AddRange(propertyValues.Load(factory, dataKey));
            work.AddRange(definitionValues.Load(factory, dataKey));
            work.AddRange(subjectAreaValues.Load(factory, dataKey));
            return work;
        }

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Load(IDatabaseWork factory, IModelIndex dataKey, ITemporalIndex asOfUtcDate)
        {
            List<WorkItem> work = new List<WorkItem>();
            work.AddRange(Delete(dataKey));
            work.AddRange(attributeValues.Load(factory, dataKey, asOfUtcDate));
            work.AddRange(aliasValues.Load(factory, dataKey, asOfUtcDate));
            work.AddRange(propertyValues.Load(factory, dataKey, asOfUtcDate));
            work.AddRange(definitionValues.Load(factory, dataKey, asOfUtcDate));
            work.AddRange(subjectAreaValues.Load(factory, dataKey, asOfUtcDate));
            return work;
        }

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Load(IDatabaseWork factory, IAttributeIndex dataKey)
        {
            List<WorkItem> work = new List<WorkItem>();
            work.AddRange(Delete(dataKey));
            work.AddRange(attributeValues.Load(factory, dataKey));
            work.AddRange(aliasValues.Load(factory, dataKey));
            work.AddRange(propertyValues.Load(factory, dataKey));
            work.AddRange(definitionValues.Load(factory, dataKey));
            work.AddRange(subjectAreaValues.Load(factory, dataKey));
            return work;
        }


        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Load(IDatabaseWork factory, IAttributeIndex dataKey, ITemporalIndex asOfUtcDate)
        {
            List<WorkItem> work = new List<WorkItem>();
            work.AddRange(Delete(dataKey));
            work.AddRange(attributeValues.Load(factory, dataKey, asOfUtcDate));
            work.AddRange(aliasValues.Load(factory, dataKey, asOfUtcDate));
            work.AddRange(propertyValues.Load(factory, dataKey, asOfUtcDate));
            work.AddRange(definitionValues.Load(factory, dataKey, asOfUtcDate));
            work.AddRange(subjectAreaValues.Load(factory, dataKey, asOfUtcDate));
            return work;
        }

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Save(IDatabaseWork factory, IModelIndex dataKey)
        {
            List<WorkItem> work = new List<WorkItem>();
            work.AddRange(attributeValues.Save(factory, dataKey));
            work.AddRange(aliasValues.Save(factory, dataKey));
            work.AddRange(propertyValues.Save(factory, dataKey));
            work.AddRange(definitionValues.Save(factory, dataKey));
            work.AddRange(subjectAreaValues.Save(factory, dataKey));
            return work;
        }

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Save(IDatabaseWork factory, IAttributeIndex dataKey)
        {
            List<WorkItem> work = new List<WorkItem>();
            work.AddRange(attributeValues.Save(factory, dataKey));
            work.AddRange(aliasValues.Save(factory, dataKey));
            work.AddRange(propertyValues.Save(factory, dataKey));
            work.AddRange(definitionValues.Save(factory, dataKey));
            work.AddRange(subjectAreaValues.Save(factory, dataKey));
            return work;
        }

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Delete()
        {
            List<WorkItem> work = new List<WorkItem>();
            work.AddRange(attributeValues.Delete());
            work.AddRange(aliasValues.Delete());
            work.AddRange(propertyValues.Delete());
            work.AddRange(definitionValues.Delete());
            work.AddRange(subjectAreaValues.Delete());

            return work;
        }

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Delete(IAttributeIndex dataKey)
        {
            List<WorkItem> work = new List<WorkItem>();
            work.AddRange(attributeValues.Delete(dataKey));
            work.AddRange(aliasValues.Delete(dataKey));
            work.AddRange(propertyValues.Delete(dataKey));
            work.AddRange(definitionValues.Delete(dataKey));
            work.AddRange(subjectAreaValues.Delete(dataKey));

            return work;
        }

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<WorkItem> Delete(IModelIndex dataKey)
        { return Delete(); }
        #endregion

        #region IDataTableFile

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public IReadOnlyList<System.Data.DataTable> Export()
        {
            List<System.Data.DataTable> result = new List<System.Data.DataTable>();
            result.Add(attributeValues.ToDataTable());
            result.Add(aliasValues.ToDataTable());
            result.Add(propertyValues.ToDataTable());
            result.Add(definitionValues.ToDataTable());
            result.Add(subjectAreaValues.ToDataTable());
            return result;
        }

        /// <inheritdoc/>
        /// <remarks>Attribute</remarks>
        public void Import(System.Data.DataSet source)
        {
            attributeValues.Load(source);
            aliasValues.Load(source);
            propertyValues.Load(source);
            definitionValues.Load(source);
            subjectAreaValues.Load(source);
        }


        #endregion

        /// <inheritdoc/>
        public IEnumerable<IAttributeValue> FindAttribute(IAliasIndexName aliasIndex)
        {
            AliasIndexName key = new AliasIndexName(aliasIndex);
            return
                Values.Join(
                    Aliases.Where(w => key.Equals(w)),
                    attribute => new AttributeIndex(attribute),
                    alias => new AttributeIndex(alias),
                    (attribute, alias) => attribute).
                ToList();
        }

        /// <inheritdoc/>
        public IAttributeValue Import(AppCatalog.TableColumnAttribute source)
        {
            // Find the Attribute by Alias
            IAttributeValue attribute = source.Aliases.
                SelectMany(s => FindAttribute(new AliasIndexName(s))).
                FirstOrDefault() ??
                source.Attribute; // Use the Source Attribute.

            AttributeIndex attributeIndex = new AttributeIndex(attribute);

            // Attribute already exists, copy the source information into the existing Attribute
            if (attributeValues.FirstOrDefault(w => attributeIndex.Equals(w)) is AttributeValue value)
            {
                if (String.IsNullOrEmpty(value.AttributeDescription))
                { value.AttributeDescription = source.Attribute.AttributeDescription; }

                foreach (var property in source.Properties)
                {
                    PropertyIndex propertyIndex = new PropertyIndex(property);
                    if (Properties.FirstOrDefault(w => attributeIndex.Equals(w) && propertyIndex.Equals(w)) is not AttributePropertyValue)
                    { Properties.Add(new AttributePropertyValue(value, property) { PropertyValue = property.PropertyValue }); }
                    ;
                }

                foreach (var alias in source.Aliases)
                {
                    AliasIndex aliasIndex = new AliasIndex(alias);
                    if (Aliases.FirstOrDefault(w => attributeIndex.Equals(w) && aliasIndex.Equals(w)) is not AttributeAliasValue)
                    { Aliases.Add(new AttributeAliasValue(value, aliasIndex)); }
                }
            }
            else // Attribute does not exist, add everything
            {
                attributeValues.Add(source.Attribute);

                foreach (var item in source.Properties)
                { Properties.Add(item); }

                foreach (var item in source.Aliases)
                { Aliases.Add(item); }
            }

            return attribute;
        }

        /// <inheritdoc/>
        public void Remove(IAttributeIndex attribute)
        {
            AttributeIndex key = new AttributeIndex(attribute);
            attributeValues.Remove(key);
            aliasValues.Remove(key);
            propertyValues.Remove(key);
            definitionValues.Remove(key);
            subjectAreaValues.Remove(key);
        }

        /// <inheritdoc/>
        public void Remove(IModelIndex dataKey)
        {
            ModelIndex key = new ModelIndex(dataKey);
            attributeValues.Remove(key);
            aliasValues.Remove(key);
            propertyValues.Remove(key);
            definitionValues.Remove(key);
            subjectAreaValues.Remove(key);
        }

        /// <inheritdoc/>
        public void Clear()
        {
            attributeValues.Clear();
            aliasValues.Clear();
            propertyValues.Clear();
            definitionValues.Clear();
            subjectAreaValues.Clear();
        }

        /// <inheritdoc/>
        public void ResetBindings()
        {
            attributeValues.ResetBindings();
            aliasValues.ResetBindings();
            propertyValues.ResetBindings();
            definitionValues.ResetBindings();
            subjectAreaValues.ResetBindings();
        }

        /// <inheritdoc/>
        public ITemporalData GetTemporal(IAttributeIndex key)
        { return attributeValues.GetTemporal(key); }

        /// <inheritdoc/>
        public ITemporalData GetTemporal(IModelIndex key)
        { return attributeValues.GetTemporal(key); }
    }
}
